token_file:
  config/token.txt

prefix:
  default:
    '='

# Discord-based config
ids:
  hosts:
    - 161508165672763392
  developers:
    - 161508165672763392

# D.py setup
cogs:
  - cogs.core
  - cogs.predictions

global_coms:
  - hi
